;;; -*- Package: DE.SETF.AMQP.IMPLEMENTATION; -*-
;;;
;;; 

(in-package "DE.SETF.AMQP.IMPLEMENTATION")

(def-encodings (:amqp-1-1-0-9-0)
  ;;amqp-0-9-0.pdf  w/ clauses reordered for typecase type precedence
  (bit                amqp:bit)            ; promoted due to typecase
  (boolean            boolean              :line-code #\t)
  (short-short-uint   (unsigned-byte 8)    :line-code #\B)
  (short-short-int    (signed-byte 8)      :line-code #\b)
  (short-uint         (unsigned-byte 16)   :line-code #\u)
  (short-int          (signed-byte 16)     :line-code #\U)
  (long-uint          (unsigned-byte 32)   :line-code #\i)
  (long-int           (signed-byte 32)     :line-code #\I)
  (long-long-uint     (unsigned-byte 64)   :line-code #\l)
  (long-long-int      (signed-byte 64)     :line-code #\L)
  (float              short-float          :line-code #\f)
  (double             double-float         :line-code #\d)
  (decimal-value      amqp:decimal         :line-code #\D)
  (short-string       (amqp:string 8)      :line-code #\s)
  (long-string        (amqp:string 32)     :line-code #\S)
  (field-array        amqp:list            :line-code #\A  :codec amqp-1-1-0-9-0::buffer-list-codec)
  (timestamp          (unsigned-byte 64)   :line-code #\T)
  (field-table        amqp:table           :line-code #\F  :codec amqp-1-1-0-9-0::buffer-table-codec)
  ;; ...  pertains to argument types, which are not table fields
  (access-ticket      (unsigned-byte 16))
  (channel-id         (unsigned-byte 16))
  (class-id           (unsigned-byte 16))
  (consumer-tag       (amqp:string 8))
  (content            (vbinary 32))     ; this was in the "transfer" method, labeled "in progress" and had no type definition
  (duration           (unsigned-byte 64))
  (destination        (amqp:string 8))
  (delivery-tag       (unsigned-byte 64))
  (exchange-name      (amqp:string 8))
  (known-hosts        (amqp:string 8))
  (long               (unsigned-byte 32))
  (longlong           (unsigned-byte 64))
  (longstr            (amqp:string 32))
  (message-count      (signed-byte 32))
  (method-id          (signed-byte 16))
  (no-ack             amqp:bit)
  (no-local           amqp:bit)
  (no-wait            amqp:bit)
  (octet              (unsigned-byte 8))
  (offset             (unsigned-byte 64))
  (path               (amqp:string 8))
  (peer-properties    amqp:table           :codec amqp-1-1-0-9-0::buffer-table-codec)
  (queue-name         (amqp:string 8))
  (reference          (amqp:string 32))
  (redelivered        amqp:bit)
  (reject-code        (unsigned-byte 8))
  (reject-text        (amqp:string 8))
  (reply-code         (unsigned-byte 16))
  (reply-text         (amqp:string 8))
  (security-token     (amqp:string 32))
  (short              (unsigned-byte 16))
  (shortstr           (amqp:string 8))
  (table              amqp:table           :codec amqp-1-1-0-9-0::buffer-table-codec)
  (nil                nil                  :line-code #\V)
  )

